// <auto-generated />
using System;
using System.Collections.Generic;
using Application.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Application.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Domain.Models.Sample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("PH")
                        .HasColumnType("REAL");

                    b.Property<int>("SourcingPoint")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TDS")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("Turbidity")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasAlternateKey("Timestamp", "SourcingPoint");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("Domain.Models.SampleSetPointSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PHSettings", "Domain.Models.SampleSetPointSettings.PHSettings#SampleMetricSetPointSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("IsEnabled")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("LowerBound")
                                .HasColumnType("REAL");

                            b1.Property<double>("UpperBound")
                                .HasColumnType("REAL");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TDSSettings", "Domain.Models.SampleSetPointSettings.TDSSettings#SampleMetricSetPointSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("IsEnabled")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("LowerBound")
                                .HasColumnType("REAL");

                            b1.Property<double>("UpperBound")
                                .HasColumnType("REAL");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TemperatureSettings", "Domain.Models.SampleSetPointSettings.TemperatureSettings#SampleMetricSetPointSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("IsEnabled")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("LowerBound")
                                .HasColumnType("REAL");

                            b1.Property<double>("UpperBound")
                                .HasColumnType("REAL");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TurbiditySettings", "Domain.Models.SampleSetPointSettings.TurbiditySettings#SampleMetricSetPointSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("IsEnabled")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("LowerBound")
                                .HasColumnType("REAL");

                            b1.Property<double>("UpperBound")
                                .HasColumnType("REAL");
                        });

                    b.HasKey("Id");

                    b.ToTable("SampleSetPointSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
